import {
  Baby,
  Banknote,
  BedDouble,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Car,
  Clapperboard,
  Coffee,
  Coins,
  CreditCard,
  Droplets,
  Dumbbell,
  Ellipsis,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  HandCoins,
  Heart,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Music,
  Package,
  Palette,
  PawPrint,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Receipt,
  Repeat,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  Sprout,
  Stethoscope,
  Tag,
  Ticket,
  TrainFront,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  User,
  Utensils,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from 'lucide-react';

/**
 * Icons a category may use. Categories store the string key; the key is
 * validated against this map so arbitrary values never reach the UI.
 */
export const CATEGORY_ICONS = {
  utensils: Utensils,
  'shopping-basket': ShoppingBasket,
  plane: Plane,
  'shopping-bag': ShoppingBag,
  house: House,
  zap: Zap,
  wifi: Wifi,
  smartphone: Smartphone,
  clapperboard: Clapperboard,
  'graduation-cap': GraduationCap,
  'heart-pulse': HeartPulse,
  repeat: Repeat,
  user: User,
  ellipsis: Ellipsis,
  briefcase: Briefcase,
  laptop: Laptop,
  building: Building2,
  'trending-up': TrendingUp,
  gift: Gift,
  coins: Coins,
  car: Car,
  fuel: Fuel,
  bus: Bus,
  train: TrainFront,
  bike: Bike,
  truck: Truck,
  coffee: Coffee,
  pizza: Pizza,
  wine: Wine,
  baby: Baby,
  'paw-print': PawPrint,
  shirt: Shirt,
  scissors: Scissors,
  sparkles: Sparkles,
  dumbbell: Dumbbell,
  pill: Pill,
  stethoscope: Stethoscope,
  'book-open': BookOpen,
  music: Music,
  'gamepad-2': Gamepad2,
  tv: Tv,
  ticket: Ticket,
  bed: BedDouble,
  heart: Heart,
  landmark: Landmark,
  'piggy-bank': PiggyBank,
  'credit-card': CreditCard,
  banknote: Banknote,
  'hand-coins': HandCoins,
  receipt: Receipt,
  shield: Shield,
  umbrella: Umbrella,
  wrench: Wrench,
  plug: Plug,
  droplets: Droplets,
  flame: Flame,
  package: Package,
  palette: Palette,
  globe: Globe,
  sprout: Sprout,
  trophy: Trophy,
  tag: Tag,
};

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICONS);

export const FALLBACK_CATEGORY_ICON = 'tag';

export function isCategoryIconKey(value) {
  return Object.hasOwn(CATEGORY_ICONS, value);
}

export function getCategoryIcon(key) {
  return CATEGORY_ICONS[key] ?? CATEGORY_ICONS[FALLBACK_CATEGORY_ICON];
}
